=== fairfield-programming/license-list/license-schema.json
{
    "$id": "https://github.com/fairfield-programming/openlist/blob/main/license-schema.json",
    "$schema": "http://json-schema.org/schema",
    "title": "FPA License Schema",
    "description": "A featured and verbose schema for describing open-source, source-available, and commercial licenses.",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "title": "FPA License Identifier"
        },
        "name": {
            "type": "string",
            "title": "License Name or Title"
        },
        "creator": {
            "type": [
                "string",
                "array"
            ],
            "title": "The Author, Creator, Editor, or Publisher of the License"
        },
        "since": {
            "type": [
                "null",
                "string",
                "integer"
            ],
            "title": "Release Date of the License"
        },
        "description": {
            "type": "string",
            "title": "Description of the Usage and History of the License"
        },
        "permissions": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "commercial-use",
                    "distribution",
                    "modification",
                    "private-use",
                    "patent-use"
                ]
            },
            "title": "License Permissions"
        },
        "conditions": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "license-notice",
                    "copyright-notice",
                    "state-changes",
                    "disclose-source",
                    "same-license-library",
                    "same-license-file",
                    "same-license",
                    "network-use-is-distribution"
                ]
            },
            "title": "License Conditions"
        },
        "limitations": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "liability",
                    "warranty",
                    "trademark-usage"
                ]
            },
            "title": "License Limitations"
        },
        "body": {
            "type": [
                "string",
                "array"
            ],
            "minLength": 4,
            "maxLength": 1000000,
            "title": "License Body"
        },
        "type": {
            "type": "string",
            "enum": [
                "open-source",
                "source-available",
                "commercial"
            ],
            "title": "License Type"
        }
    }
}

=== fairfield-programming/license-list/licenses/mit-modern-variant.json
{
    "id": "mit-modern-variant",
    "name": "MIT License Modern Variant",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright Â© 1990-2021 The Regents of the University of California. All rights reserved.\n\nPermission is hereby granted, without written agreement and without license or royalty fees, to use, copy, modify, and distribute this software and its documentation for any purpose, provided that the above copyright notice and the following two paragraphs appear in all copies of this software.\n\nIN NO EVENT SHALL <-<THE UNIVERSITY OF CALIFORNIA>-> BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF <-<THE UNIVERSITY OF CALIFORNIA>-> HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\n<-<THE UNIVERSITY OF CALIFORNIA>-> SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN \"AS IS\" BASIS, AND <-<THE UNIVERSITY OF CALIFORNIA>-> HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/app-s2p.json
{
    "id": "app-s2p",
    "name": "App::s2p License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "COPYRIGHT and LICENSE\n\nThis program is free and open software. You may use, modify, distribute, and sell this program (and any modified variants) in any way you wish, provided you do not restrict others from doing the same.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/dotseqn.json
{
    "id": "dotseqn",
    "name": "Dotseqn License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright (C) 1995 by Donald Arseneau\n\nThis file may be freely transmitted and reproduced, but it may not be changed unless the name is changed also (except that you may freely change the paper-size option for \\documentclass).\n\nThis notice must be left intact.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/blessing.json
{
    "id": "blessing",
    "name": "SQLite Blessing",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "The author disclaims copyright to this source code. In place of a legal notice, here is a blessing:\n\nMay you do good and not evil.\nMay you find forgiveness for yourself and forgive others.\nMay you share freely, never taking more than you give.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/diffmark.json
{
    "id": "diffmark",
    "name": "diffmark license",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "1. you can do what you want with it\n2. I refuse any responsibility for the consequences",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/lzma-sdk-9.11-to-9.20.json
{
    "id": "lzma-sdk-9.11-to-9.20",
    "name": "LZMA SDK License (versions 9.11 to 9.20)",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "LZMA SDK is written and placed in the public domain by Igor Pavlov.\n\nSome code in LZMA is based on public domain code from another developers: 1) PPMd var.H (2001): Dmitry Shkarin 2) SHA-256: Wei Dai (Crypto++ library)",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/spencer-86.json
{
    "id": "spencer-86",
    "name": "Spencer License 86",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright (c) 1986 by University of Toronto. Written by Henry Spencer. Not derived from licensed software.\n\nPermission is granted to anyone to use this software for any purpose on any computer system, and to redistribute it freely, subject to the following restrictions:\n\n1. The author is not responsible for the consequences of use of this software, no matter how awful, even if they arise from defects in it.\n2. The origin of this software must not be misrepresented, either by explicit claim or by omission.\n3. Altered versions must be plainly marked as such, and must not be misrepresented as being the original software.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/glwtpl.json
{
    "id": "glwtpl",
    "name": "Good Luck With That Public License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright (c) Everyone, except Author\n\nEveryone is permitted to copy, distribute, modify, merge, sell, publish, sublicense or whatever they want with this software but at their OWN RISK.\n\nPreamble\n\nThe author has absolutely no clue what the code in this project does. It might just work or not, there is no third option.\n\nGOOD LUCK WITH THAT PUBLIC LICENSE\n\nTERMS AND CONDITIONS FOR COPYING, DISTRIBUTION, AND MODIFICATION\n\n0. You just DO WHATEVER YOU WANT TO as long as you NEVER LEAVE A TRACE TO TRACK THE AUTHOR of the original product to blame for or hold responsible.\n\nIN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nGood luck and Godspeed.",
    "type": "source-available"
}
