=== fairfield-programming/license-list/license-schema.json
{
    "$id": "https://github.com/fairfield-programming/openlist/blob/main/license-schema.json",
    "$schema": "http://json-schema.org/schema",
    "title": "FPA License Schema",
    "description": "A featured and verbose schema for describing open-source, source-available, and commercial licenses.",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "title": "FPA License Identifier"
        },
        "name": {
            "type": "string",
            "title": "License Name or Title"
        },
        "creator": {
            "type": [
                "string",
                "array"
            ],
            "title": "The Author, Creator, Editor, or Publisher of the License"
        },
        "since": {
            "type": [
                "null",
                "string",
                "integer"
            ],
            "title": "Release Date of the License"
        },
        "description": {
            "type": "string",
            "title": "Description of the Usage and History of the License"
        },
        "permissions": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "commercial-use",
                    "distribution",
                    "modification",
                    "private-use",
                    "patent-use"
                ]
            },
            "title": "License Permissions"
        },
        "conditions": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "license-notice",
                    "copyright-notice",
                    "state-changes",
                    "disclose-source",
                    "same-license-library",
                    "same-license-file",
                    "same-license",
                    "network-use-is-distribution"
                ]
            },
            "title": "License Conditions"
        },
        "limitations": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "liability",
                    "warranty",
                    "trademark-usage"
                ]
            },
            "title": "License Limitations"
        },
        "body": {
            "type": [
                "string",
                "array"
            ],
            "minLength": 4,
            "maxLength": 1000000,
            "title": "License Body"
        },
        "type": {
            "type": "string",
            "enum": [
                "open-source",
                "source-available",
                "commercial"
            ],
            "title": "License Type"
        }
    }
}

=== fairfield-programming/license-list/licenses/borceux.json
{
    "id": "borceux",
    "name": "Borceux license",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright 1993 Francis Borceux\n\nYou may freely use, modify, and/or distribute each of the files in this package without limitation. The package consists of the following files: README compatibility/OldDiagram compatibility/OldMaxiDiagram compatibility/OldMicroDiagram compatibility/OldMiniDiagram compatibility/OldMultipleArrows diagram/Diagram diagram/MaxiDiagram diagram/MicroDiagram diagram/MiniDiagram diagram/MultipleArrows user-guides/Diagram_Mode_d_Emploi user-guides/Diagram_Read_Me\n\nOf course no support is guaranteed, but the author will attempt to assist with problems. Current email address: francis dot borceux at uclouvain dot be.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/gl2ps.json
{
    "id": "gl2ps",
    "name": "GL2PS License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright (C) 2003, Christophe Geuzaine\n\nPermission to use, copy, and distribute this software and its documentation for any purpose with or without fee is hereby granted, provided that the copyright notice appear in all copies and that both that copyright notice and this permission notice appear in supporting documentation.\n\nPermission to modify and distribute modified versions of this software is granted, provided that:\n\n1) the modifications are licensed under the same terms as this software;\n2) you make available the source code of any modifications that you distribute, either on the same media as you distribute any executable or other form of this software, or via a mechanism generally accepted in the software development community for the electronic transfer of data.\n\nThis software is provided \"as is\" without express or implied warranty.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/x11-distribute-modifications-variant.json
{
    "id": "x11-distribute-modifications-variant",
    "name": "X11 License Distribution Modification Variant",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright (c) <year> <copyright holders>\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, distribute with modifications, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nExcept as contained in this notice, the name(s) of the above copyright holders shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Software without prior written authorization.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/ttwl.json
{
    "id": "ttwl",
    "name": "Text-Tabs+Wrap License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright (C) 1996-2002,2005,2006 David Muir Sharnoff. Copyright (C) 2005 Aristotle Pagaltzis Copyright (C) 2012-2013 Google, Inc.\n\nThis module may be modified, used, copied, and redistributed at your own risk. Although allowed by the preceding license, please do not publicly redistribute modified versions of this code with the name \"Text::Tabs\" unless it passes the unmodified Text::Tabs test suite.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/mplus.json
{"id":"mplus","name":"mplus Font License","creator":[],"since":"","description":"The Mplus font licence enables users to confidently and easily incorporate the typeface into a variety of projects, both personal and professional.It is an adaptable and stylish font that has become more well-liked among designers and other creatives around the world.","permissions":["distribution","private-use"],"conditions":[],"limitations":["warranty"],"body":"These fonts are free softwares. Unlimited permission is granted to use, copy, and distribute it, with or without modification, either commercially and noncommercially. THESE FONTS ARE PROVIDED \"AS IS\" WITHOUT WARRANTY.","type":"source-available"}

=== fairfield-programming/license-list/licenses/ntp-0.json
{
    "id": "ntp-0",
    "name": "NTP No Attribution",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright (4-digit-year) by (CopyrightHoldersName)\n\nPermission to use, copy, modify, and distribute this software and its documentation for any purpose is hereby granted, provided that the name ?-?s?-? of <-<(TrademarkedName)>-> not be used in advertising or publicity pertaining to distribution of the software without specific, written prior permission. <-<(TrademarkedName)>-> make ?-?s?-? no representations about the suitability of this software for any purpose. It is provided \"as is\" without express or implied warranty.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/wtfpl.json
{
    "id": "wtfpl",
    "name": "Do What The F*ck You Want To Public License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>\n\nEveryone is permitted to copy and distribute verbatim or modified copies of this license document, and changing it is allowed as long as the name is changed.\n\nDO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n\n0. You just DO WHAT THE FUCK YOU WANT TO.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/cube.json
{
    "id": "cube",
    "name": "Cube License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright (C) 2001-2003 Wouter van Oortmerssen.\n\nThis software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.\n\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:\n\n1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.\n2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.\n3. This notice may not be removed or altered from any source distribution.\n\nadditional clause specific to Cube:\n\n4. Source versions may not be \"relicensed\" under a different license without my explicitly written permission.",
    "type": "source-available"
}
