=== fairfield-programming/license-list/license-schema.json
{
    "$id": "https://github.com/fairfield-programming/openlist/blob/main/license-schema.json",
    "$schema": "http://json-schema.org/schema",
    "title": "FPA License Schema",
    "description": "A featured and verbose schema for describing open-source, source-available, and commercial licenses.",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "title": "FPA License Identifier"
        },
        "name": {
            "type": "string",
            "title": "License Name or Title"
        },
        "creator": {
            "type": [
                "string",
                "array"
            ],
            "title": "The Author, Creator, Editor, or Publisher of the License"
        },
        "since": {
            "type": [
                "null",
                "string",
                "integer"
            ],
            "title": "Release Date of the License"
        },
        "description": {
            "type": "string",
            "title": "Description of the Usage and History of the License"
        },
        "permissions": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "commercial-use",
                    "distribution",
                    "modification",
                    "private-use",
                    "patent-use"
                ]
            },
            "title": "License Permissions"
        },
        "conditions": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "license-notice",
                    "copyright-notice",
                    "state-changes",
                    "disclose-source",
                    "same-license-library",
                    "same-license-file",
                    "same-license",
                    "network-use-is-distribution"
                ]
            },
            "title": "License Conditions"
        },
        "limitations": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "liability",
                    "warranty",
                    "trademark-usage"
                ]
            },
            "title": "License Limitations"
        },
        "body": {
            "type": [
                "string",
                "array"
            ],
            "minLength": 4,
            "maxLength": 1000000,
            "title": "License Body"
        },
        "type": {
            "type": "string",
            "enum": [
                "open-source",
                "source-available",
                "commercial"
            ],
            "title": "License Type"
        }
    }
}

=== fairfield-programming/license-list/licenses/tcp-wrappers.json
{
    "id": "tcp-wrappers",
    "name": "TCP Wrappers License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright 1995 by Wietse Venema. All rights reserved. Some individual files may be covered by other copyrights.\n\nThis material was originally written and compiled by Wietse Venema at Eindhoven University of Technology, The Netherlands, in 1990, 1991, 1992, 1993, 1994 and 1995.\n\nRedistribution and use in source and binary forms, with or without modification, are permitted provided that this entire copyright notice is duplicated in all such copies.\n\nThis software is provided \"as is\" and without any expressed or implied warranties, including, without limitation, the implied warranties of merchantibility and fitness for any particular purpose.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/tu-berlin-2.0.json
{
    "id": "tu-berlin-2.0",
    "name": "Technische Universitaet Berlin License 2.0",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright 1992, 1993, 1994 by Jutta Degener and Carsten Bormann, Technische Universitaet Berlin\n\nAny use of this software is permitted provided that this notice is not removed and that neither the authors nor the Technische Universitaet Berlin are deemed to have made any representations as to the suitability of this software for any purpose nor are held responsible for any defects of this software. THERE IS ABSOLUTELY NO WARRANTY FOR THIS SOFTWARE.\n\nAs a matter of courtesy, the authors request to be informed about uses this software has found, about bugs in this software, and about any improvements that may be of general interest.\n\n?-?Berlin, <-<28.11.1994>-> Jutta Degener Carsten Bormann?-?\n\n?-?oOo?-?\n\nSince the original terms of 15 years ago maybe do not make our intentions completely clear given today's refined usage of the legal terms, we append this additional permission:\n\nPermission to use, copy, modify, and distribute this software for any purpose with or without fee is hereby granted, provided that this notice is not removed and that neither the authors nor the Technische Universitaet Berlin are deemed to have made any representations as to the suitability of this software for any purpose nor are held responsible for any defects of this software. THERE IS ABSOLUTELY NO WARRANTY FOR THIS SOFTWARE.\n\n?-?Berkeley/Bremen, <-<05.04.2009>-> Jutta Degener Carsten Bormann?-?",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/knuth-ctan.json
{
    "id": "knuth-ctan",
    "name": "Knuth CTAN License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "This software is copyrighted. Unlimited copying and redistribution of this package and/or its individual files are permitted as long as there are no modifications. Modifications, and redistribution of modifications, are also permitted, but only if the resulting package and/or files are renamed.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/bsd-3-clause-modification.json
{
    "id": "bsd-3-clause-modification",
    "name": "BSD 3-Clause Modification",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:\n\n1. Redistributions in source code must retain the accompanying copyright notice, this list of conditions, and the following disclaimer.\n2. Redistributions in binary form must reproduce the accompanying copyright notice, this list of conditions, and the following disclaimer in the documentation and/or other materials provided with the distribution.\n3. Names of the copyright holders must not be used to endorse or promote products derived from this software without prior written permission from the copyright holders.\n4. If any files are modified, you must cause the modified files to carry prominent notices stating that you changed the files and the date of any change.\n\nDisclaimer\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS \"AS IS\" AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/tpdl.json
{
    "id": "tpdl",
    "name": "Time::ParseDate License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "Copyright (C) 1996-2010 David Muir Sharnoff. Copyright (C) 2011 Google, Inc.\n\nLicense hereby granted for anyone to use, modify or redistribute this module at their own risk. Please feed useful changes back to cpan@dave.sharnoff.org.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/dvipdfm.json
{
    "id": "dvipdfm",
    "name": "dvipdfm License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "A modified version of this file may be distributed, but it should be distributed with a *different* name. Changed files must be distributed *together with a complete and unchanged* distribution of these files.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/zed.json
{
    "id": "zed",
    "name": "Zed License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "(c) Jim Davies, January 1995\n\nYou may copy and distribute this file freely. Any queries and complaints should be forwarded to Jim.Davies@comlab.ox.ac.uk.\n\nIf you make any changes to this file, please do not distribute the results under the name `zed-csp.sty'.",
    "type": "source-available"
}

=== fairfield-programming/license-list/licenses/nlpl.json
{
    "id": "nlpl",
    "name": "No Limit Public License",
    "creator": [],
    "since": "",
    "description": "",
    "permissions": [],
    "conditions": [],
    "limitations": [],
    "body": "?-?Gilles LAMIRAL La Billais 35580 Baulon France?-?\n\nTerms and conditions for copying, distribution, modification or anything else.\n\n0. No limit to do anything with this work and this license.",
    "type": "source-available"
}
